name: update-cache
#When cached from an overhead branch, 
#sub branches should refer to overhead branch when checking cache hit

on:
  push:
    branches: [main, master]

jobs:
  build-cache:
    name: Build Cache
    runs-on: ubuntu-latest

    steps:
      name: Setup R
      uses: r-lib/actions/setup-r@v2

      name: Checkout Rep
      uses: actions/checkout@v2

      #Cache Dependencies to speed up workflow
      name: Cache dependencies
      uses: actions/cache@v1
      id: cache
      with:
        path: ${{ env.R_LIBS_USER }}
        key:  r-${{ hashFiles('DESCRIPTION') }}
        restore-keys:
          ${{ env.R_LIBS_USER }}

      #If no cache hit, install dependencies
      name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      #run: