name: Pull requests

# Controls when the action will run. 
on:
  # Triggers the workflow pull request events
  pull_request: {}
    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository so your job can access it
      - uses: actions/checkout@v2

      #- name: Cache R packages
      #- uses: actions/cache@v1
      #  with:
          
      # build the docker image and give it the name main
      - name: Build image
        run: docker build -t pullrequestimage . 
      # run the docker image supply the secrets from the github secrets store.  
      - name: execute
        run: >
          docker run 
          -e SHINY_ACC_NAME=${{ secrets.SHINY_ACC_NAME }} 
          -e TOKEN=${{secrets.SHINY_APP_TOKEN}} 
          -e SECRET=${{secrets.SHINY_APP_SECRET}} 
          -e MASTERNAME=Testing
          pullrequestimage